### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Mwandia** [IntaSend/intasend-node#1]
## Feature Request

Add typescript support.

## Motivation
Typescript is becoming the main language of choice in development of frontends and nodejs enabled backend APIs. Adding support would allow more flexibility in the choice of language specification in the javascript space.

## Contribution

Add types and restructure project allowing package typescript support.

**Comment by sr-04** [comment]
Hii, can I get more info about the project? I would like to contribute.

**Comment by mwandia** [comment]
@sr-04 this is the source code for the javascript client for intasend, a payment processing platform.
I'm creating a PR for this, will add you to check out the changes.

**Comment by sr-04** [comment]
yes sure!!

**Comment by sr-04** [comment]
also as I can see this project used class based structure do you want me to change it to function based as it is generally used these days.

**Comment by mwandia** [comment]
Better to separate that into another issue and PR

**Comment by sr-04** [comment]
okay cool. I have made the basic changes in the JS files to typescript, adding types and restructuring a little bit according to typescript requirements. I will get back to you after the final check and changes tomorrow.

**Comment by felixcheruiyot** [comment]
Hi @sr-04 and @Mwandia thank you for raising this issue and the willingness to assist. Kindly let me know how it is coming along. @sr-04 feel free to open a pull request when ready.
